# Generated by Django 4.2.11 on 2026-03-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('entry_point', models.CharField(max_length=255)),
                ('interval_minutes', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('is_part_time', models.BooleanField(default=False)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('relevance_score', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('customized_cv_path', models.FileField(blank=True, null=True, upload_to='custom_cvs/')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ANALYZED', 'Analyzed'), ('CV_GENERATED', 'CV Generated'), ('APPLIED', 'Applied'), ('FAILED', 'Failed')], default='NEW', max_length=20)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
