# Generated by Django 4.2.11 on 2026-03-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='experience_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('MID', 'Mid Level'), ('SENIOR', 'Senior')], default='MID', max_length=20),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='source',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
